pipeline:
  name: test-zx
  identifier: testzx
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: zx
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: checkout
                  identifier: builds
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: plugins/github-actions
                    privileged: true
                    settings:
                      uses: actions/checkout@v3
              - parallel:
                  - step:
                      type: Run
                      name: build check
                      identifier: testubuntu
                      spec:
                        shell: Sh
                        command: |-
                          npm i
                          npm run build:check
                  - step:
                      type: Run
                      name: circular
                      identifier: circular
                      spec:
                        shell: Sh
                        command: |-
                          npm i
                          npm run circular
              - parallel:
                  - step:
                      type: Run
                      name: code-style
                      identifier: codestyle
                      spec:
                        shell: Sh
                        command: |-
                          npm i
                          # npm run fmt:check
                  - step:
                      type: Run
                      name: types
                      identifier: types
                      spec:
                        shell: Sh
                        command: |-
                          npm run build
                          npm run test:types
              - step:
                  type: Run
                  name: coverage
                  identifier: coverage
                  spec:
                    shell: Sh
                    command: |-
                      npm i
                      npm run coverage
                    envVariables:
                      FORCE_COLOR: "3"
                  timeout: 1m
        when:
          pipelineStatus: All
